info.app:
  name: Prompt picture app

spring:
  codec:
    max-in-memory-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5001/prompt?currentSchema=public
    username: prompt
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  quartz:
    job-store-type: jdbc
    jdbc.initialize-schema: always
    properties.org.quartz:
      scheduler:
        instanceId: AUTO
        instanceName: prompt-quartz
      threadPool.threadCount: 100
      jobStore:
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        useProperties: false
        misfireThreshold: 60000
        tablePrefix: qrtz_
        isClustered: true
      plugin.shutdownHook:
        class: org.quartz.plugins.management.ShutdownHookPlugin
        cleanShutdown: TRUE
    properties:
      org.quartz.jobStore.isClustered: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

app:
  delle:
    baseUrl: https://api.openai.com
    accessToken: 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
